eks:
  node_size: t3.medium
  min_nodes: 2
  max_nodes: 10

sqs_queues:
  _templates:
    standard:
      retention: 86400
      dlq: true
      visibility_timeout: 30
    high_retention:
      retention: 604800
      dlq: true
      visibility_timeout: 30
    critical:
      retention: 604800
      dlq: true
      visibility_timeout: 30
      dlq_max_retries: 5

  orders:
    _inherit:
      - template: standard
        except:
          - dlq
      - template: critical
  notifications:
    _inherit: standard
